theme: blowfish
baseURL: "https://vivian-1372.github.io/Political-Psychology/"
defaultContentLanguage: en
enableRobotsTXT: yes
paginate: 20
summaryLength: 30
# changed to yes to reconcile public/content posts
buildDrafts: yes
buildFuture: no
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5
outputs:
  home:
    - HTML
    - RSS
    - JSON
